### PR TITLE
Modernize plugin

### PR DESCRIPTION
**Pull request by basil**
Updates this plugin's build toolchain and dependencies to the latest versions.

### CODE REVIEW

**Comment by basil** [comment]
Used my admin powers to replay the build with the `Jenkinsfile` changes here: https://ci.jenkins.io/job/Plugins/job/ansicolor-plugin/job/PR-258/2/

**Comment by dblock** [comment]
So, no?

**Comment by basil** [comment]
This PR has been closed.

**Comment by dblock** [comment]
I am curious why you closed it. The upgrade made sense to me.

**Comment by basil** [comment]
I am not interested in working on this change further. Keeping the plugin up-to-date is the responsibility of the maintainers, not me.

**Comment by dblock** [comment]
I'm not interested supporting @cloudbees business for free.

**Comment by basil** [comment]
Whatever contributions you make, large or small, they will be appreciated.

**Pull request closed without merging**
