### PR TITLE
Refresh dependencies and enable dependabot

### PR DESCRIPTION
**Pull request by jonesbusy**
Hi,

Build against modern Jenkins (drop Java 8 support)

Regards,

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did

### CODE REVIEW

**Comment by dblock** [comment]
Thanks. Let's merge this on green. 

If we drop JDK8 support I think we need to increment major version.

**Comment by jonesbusy** [comment]
```
07:29:31  Loading trusted files from base branch master at 49e7aa0bd6256cfe175ec1f28b23c8b7a4494f46 rather than 736087cc67c3dd6d6e8c88e952ae5b4fc5b8b177
07:29:32  Obtained Jenkinsfile from 49e7aa0bd6256cfe175ec1f28b23c8b7a4494f46
07:29:32  ‘Jenkinsfile’ has been modified in an untrusted revision
```

Jenkinsfile must be pushed by a maintainer. Ideally on main and I can rebase this PR.

Builds are failing on Java 8 because of this

**Comment by dblock** [comment]
Let's see if it likes https://github.com/jenkinsci/ansicolor-plugin/pull/254 better.

**Comment by dblock** [comment]
Looks like there are legit failures. If you want to split some things out, like dependabot, make separate PRs, I'd be happy to merge.

**Pull request closed without merging**
