### PR TITLE
Add Jenkinsfile

### PR DESCRIPTION
**Pull request by olivergondza**

### CODE REVIEW

**Comment by dblock** [comment]
Care to tell us why we want one?

**Comment by olivergondza** [comment]
In order to have tests executed on https://ci.jenkins.io/job/Plugins/. I will leave it up to the maintainer(s) to decide whether it is desirable to have alongside the travis build or not.

**Comment by dblock** [comment]
I'm going to call it as unnecessary overhead unless someone wants to setup and maintain that fully, with badges, github integration, etc.

**Comment by olivergondza** [comment]
@dblock, FTR, it does all that, just check some existing plugin that have it configured: https://github.com/jenkinsci/junit-plugin/. Though, as I said, I am leaving that up to you.

**Pull request closed without merging**
