### PR TITLE
212 partial log output

### LINKED ISSUE #212: Logs not showing colors
### Test environment
```
- Jenkins Version:2.263.1
- AnsiColor Version:0.7.3
- Operating System running Jenkins: Ubuntu 14.04.6 LTS
```

### Expected behavior
see logs similar to full log screen 
image

### Actual behavior
Logs not showing colors (do show in Full log mode/screen),
image

### Steps to reproduce the behavior
free style project, 
execute shell 
echo '\033[42m\033[97mWhite letters, green background\033[0m'
 
image
image
image

### Issue checklist

- [x] Jenkins version
- [x] AnsiColor version
- [x] Operating System name and version
- [x] Expected behavior
- [x] Actual behavior
- [x] Steps to reproduce the behavior

### PR DESCRIPTION
**Pull request by tszmytka**
Fixes #212

### CODE REVIEW

**Comment by AvihayTsayeg** [comment]
Hi @tszmytka ,
first would like to thank u for quick response and fixing, I have tested your fix, it do fix the echo example I have added, but it did not fix the build which due I opened the issue.

OK:
image

Still not working:
image

**Comment by tszmytka** [comment]
@AvihayTsayeg Please provide the script that causes the problem **in the original issue**. 
This PR fixes a valid bug even if it isn't *your* bug.

**Comment by dblock** [comment]
I'll merge this cause it does look like an issue, and thanks for fixing it @tszmytka!

Consider beefing up tests with empty lines. I am always worried about those index calculations ;)

**Comment by avihaycloudinary** [comment]
@dblock 
Many thanks, I will add more details.
Thank u @tszmytka

**Comment by AvihayTsayeg** [comment]
see https://github.com/jenkinsci/ansicolor-plugin/issues/216

**Comment by timja** [comment]
I think this may have caused tests to break for this plugin on the latest LTS,

See https://github.com/jenkinsci/bom/pull/402

**Pull request merged**
