### PR TITLE
Modernize to Jenkins 2.440.3

### PR DESCRIPTION
**Pull request by sghill-rewrite**
Hi!

This PR aims to move this plugin to the [recommended](https://www.jenkins.io/doc/developer/plugin-development/choosing-jenkins-baseline/) Jenkins baseline version.

If there are additional requirements for accepting PRs - such as additional lag time before adopting a baseline - feel free to reply in the comments.

## Testing done
Ran `mvn clean verify`.

```[tasklist]
### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

Refs: sghill-rewrite/campaigns#4

Use this link to re-run the recipe: https://app.moderne.io/recipes/org.openrewrite.jenkins.ModernizePlugin?organizationId=SmVua2lucyBDSQ%3D%3D

### CODE REVIEW

**Comment by dblock** [comment]
Does this increment the minimal version of Jenkins required? Any reason not to?

**Comment by sghill** [comment]
It does increase the required Jenkins version to 2.440.3 (released April 2024). Users on older versions of Jenkins would only be able to install earlier versions of this plugin.

Some folks have a preference to wait longer. Personally I think supporting the last couple LTS releases (as this PR does) makes sense. There are important fixes happening all the time in Jenkins, and the longer users wait to upgrade, the harder the upgrade becomes.

Hope that helps. If you have other preferences I'm happy to record them so the tooling won't bug you again with an unwanted upgrade.

**Comment by dblock** [comment]
April feels recent, but what versions are LTS?

**Comment by sghill** [comment]
The weekly releases all have 2 components (2.440). Once one is chosen to be a LTS, it gets a patch component (2.440.1). There are 3-4 LTS patches before support is dropped and a new weekly release becomes LTS. 

The change log is here: https://www.jenkins.io/changelog-stable/

**Pull request merged**
