### PR TITLE
Bump plugin parent POM from 3.25 to 3.48

### PR DESCRIPTION
**Pull request by basil**
Bumps the [plugin parent POM](https://github.com/jenkinsci/plugin-pom) from 3.25 to 3.48.

See [the changelog](https://github.com/jenkinsci/plugin-pom/blob/master/CHANGELOG.md) and the full diff in [the compare view](https://github.com/jenkinsci/plugin-pom/compare/plugin-3.25...plugin-3.48).

### CODE REVIEW

**Comment by basil** [comment]
Test failure is due to:

```
$ ~/bin/install-jdk.sh --target "/home/travis/oraclejdk8" --workspace "/home/travis/.cache/install-jdk" --feature "8" --license "BCL"
Ignoring license option: BCL -- using GPLv2+CE by default
install-jdk.sh 2019-07-17
Expected feature release number in range of 9 to 14, but got: 8
The command "~/bin/install-jdk.sh --target "/home/travis/oraclejdk8" --workspace "/home/travis/.cache/install-jdk" --feature "8" --license "BCL"" failed and exited with 3 during .
```

This doesn't look related to this change.

**Comment by dblock** [comment]
Not sure what the issue is, but I would merge anything green. We need to debug that before adding more changes.

**Comment by basil** [comment]
> Not sure what the issue is, but I would merge anything green. We need to debug that before adding more changes.

Thanks @dblock. Are you planning to debug this? As far as I can tell, that would be a problem on tip of trunk. I could demonstrate this would a new PR that does nothing other than change a comment, for example.

**Comment by basil** [comment]
> I could demonstrate this would a new PR that does nothing other than change a comment, for example.

Demonstrated in jenkinsci/ansicolor-plugin#162. CI is currently broken on tip of trunk for this plugin.

**Comment by dblock** [comment]
I fixed this in https://github.com/jenkinsci/ansicolor-plugin/pull/163. Rebase, squash, etc to 💚 and I'll merge.

**Comment by basil** [comment]
Thanks!

> Rebase, squash, etc to green_heart and I'll merge.

There weren't any new commits to `origin/master`, so I rebased against `dblock/openjdk-8`. The CI run is now green.

**Comment by dblock** [comment]
I had to run and forgot to hit merge :) This is now on master.

**Pull request closed without merging**
