### PR TITLE
Update plugin parent POM and plugin BOM

### PR DESCRIPTION
**Pull request by basil**

### CODE REVIEW

**Comment by basil** [comment]
Thank you, @tszmytka! A release of this would facilitate Java 17 PCT testing.

**Comment by basil** [comment]
Gentle ping; a release of this would help me move forward with some draft PRs in `jenkinsci/bom`.

**Comment by dblock** [comment]
I opened https://github.com/jenkinsci/ansicolor-plugin/issues/243

**Comment by basil** [comment]
Thanks @dblock! BTW if you implement [automated plugin release](https://www.jenkins.io/doc/developer/publishing/releasing-cd/) then releasing a plugin becomes as simple as adding a special label when merging PRs.

**Comment by dblock** [comment]
@basil Care to contribute? Let us know what you need from @tszmytka or I?

**Comment by basil** [comment]
If you are suggesting that I contribute more to Jenkins, you must not have seen my GitHub profile. I have made my contribution to this plugin. What I need from the plugin maintainers is for that contribution to be released so that I can do plugin compatibility testing with it.

**Comment by basil** [comment]
But if I propose a PR to implement automated plugin release, I risk that my time would be wasted because the maintainers do not want to use automated plugin release. The decision about whether or not to use automated plugin release belongs to the maintainers, not to me. Therefore, it makes sense for the same maintainers to implement automated plugin release. If the maintainer chooses not to implement automated plugin release, it is the maintainer's responsibility to do manual releases.

**Comment by dblock** [comment]
I am a maintainer and can confirm that we want tag-based automated plugin release.

**Comment by basil** [comment]
> I am a maintainer and can confirm that we want tag-based automated plugin release.

Then I suggest you follow the instructions in [Setting up automated plugin release ](https://www.jenkins.io/doc/developer/publishing/releasing-cd/), or (if you decline to follow those instructions) to perform a manual release. I will _not_ do this work for you. It is the responsibility of the plugin maintainer, not contributors, to handle releases.

**Comment by dblock** [comment]
@basil Thank you for your helpful suggestions. I will release this plugin sometime next month.

**Comment by basil** [comment]
> I will release this plugin sometime next month.

But two months later?

**Comment by dblock** [comment]
Well, I tried. Could use some help, https://github.com/jenkinsci/ansicolor-plugin/pull/247#issuecomment-1193322750

**Comment by basil** [comment]
> Well, I tried. Could use some help, [#247 (comment)](https://github.com/jenkinsci/ansicolor-plugin/pull/247#issuecomment-1193322750)

On July 24, I provided the help that was requested: https://github.com/jenkinsci/ansicolor-plugin/pull/247#issuecomment-1193368039

**Comment by dblock** [comment]
https://repo.jenkins-ci.org/artifactory/releases/org/jenkins-ci/plugins/ansicolor/1.0.2/

**Pull request merged**
