### PR TITLE
Add missing license info to pom.xml

### PR DESCRIPTION
**Pull request by darxriggs**
see http://maven.apache.org/pom.html#Licenses

### CODE REVIEW

**Comment by dblock** [comment]
I am not sure what the problem with the build is, but we need to fix that before taking more PRs, even trivial ones. Appreciate some help.

**Comment by dblock** [comment]
Rebase this and I'll merge on 💚. Thank you.

**Comment by darxriggs** [comment]
The PR is ready for merge now.

**Comment by dblock** [comment]
👍

**Pull request merged**
